### ISSUE TITLE
Lazy loading on filetype happens before syntax is set?

### ISSUE THREAD

**Issue by jeaye** [Shougo/neobundle.vim#431]
Hey @Shougo, excellent plugin. There's been a [long-standing issue](https://github.com/jeaye/color_coded/issues/33) with one of my plugins which I've just been able to reproduce when using neobundle's lazy loading.

My question: given the lazy loading shown below, based on filetype, what do you know of neobundle's ordering when it comes to setting up syntax? The error is happening [here](
https://github.com/jeaye/color_coded/blob/master/autoload/color_coded.vim#L112) and only happens when lazy loading is enabled.

Example config:
```viml
  NeoBundleLazy 'jeaye/color_coded', {
      \ 'build': {
      \   'unix': 'cmake . && make && make install',
      \ },
      \ 'autoload' : { 'filetypes' : ['c', 'cpp', 'objc', 'objcpp'] },
      \ 'build_commands' : ['cmake', 'make']
  \}
```

**Comment by jeaye** [comment]
Here is a trivial (26 line) vimrc which replicates the issue. Note that color_coded can take a while to install, since it downloads libclang. Upon opening a C++ file, one sees `[neobundle] Uncaught error while sourcing "color_coded": Vim(execute):E121: Undefined variable: b:current_syntax in function color_coded#enter, line 7`

**Comment by Shougo** [comment]
OK.  I will test it.

**Comment by Shougo** [comment]
I cannot test it.
Because, ..

```
$gvim -u test.vimrc6 test.cpp
 Vim: Caught deadly signal SEGV                                                                                                        
Vim: Finished.
```

It is too bad...

**Comment by Shougo** [comment]
I think it is fixed.

**Comment by Shougo** [comment]
I think color_coded plugin should check the syntax file is already sourced.
Same problem is available in Vundle and other plugin managers.

**Comment by jeaye** [comment]
On Sun, Oct 11, 2015 at 10:43:08PM -0700, Shougo wrote:
>    I think color_coded plugin should check the syntax file is already
>    sourced.
>    Same problem is available in Vundle and other plugin managers.

The issue isn't that syntax has already been sourced, since that would result in `b:current_syntax` existing. color_coded does rely on the syntax existing, yes, since it needs to invoke `ownsyntax` on each buffer. I don't see a way around that.

**Comment by jeaye** [comment]
@Shougo If color_coded is crashing for you, please take the time to work with me (or look at the README) so that we can resolve this issue. I can say that, even with the latest neobundle master, lazy loading color_coded still shows that `b:current_syntax` is set.

1. A simple test on your end would be to print `b:current_syntax` [here](https://github.com/Shougo/neobundle.vim/commit/0a682118a469fa04b823ba0487ad4142f0b8a459#diff-802023f1138b3c2c343944cf07809218R225)
2. My guess, based on your crash is that you're using luajit, which doesn't support being embedded in a native shared object (thus is incompatible with color_coded)

If you're not interested in giving color_coded a proper shot, please give 1) a look on your end so you can also verify that `b:current_syntax` is not yet set.

**Comment by Shougo** [comment]
> My guess, based on your crash, is that you're using luajit, which doesn't support being embedded in a native shared object (thus is incompatible with color_coded)

OH, it is bad.  I use luajit based if_lua.

**Comment by Shougo** [comment]
@jeaye OK.  I get it.
You must specify augroup attribute.

```
						*neobundle-options-augroup*
		augroup		(String)
		Specify an augroup name that the plugin uses for |VimEnter| or
		|GUIEnter| autocmd events.
		Neobundle will call their |VimEnter| or |GUIEnter| autocmds
		automatically when |:NeoBundleSource| is executed.
		Note: You'll want to set this option because some plugins
		rely on autocmds defined for |VimEnter| or |GUIEnter|, but by
		using |:NeoBundleSource| after loading .vimrc, those autocmds
		may get skipped
skipped. Some examples are, "fugitive", "NERDTree",
		and "session.vim".
```

Because, color_coded uses VimEnter autocmd to load
after/syntax/color_coded.vim.

```
NeoBundleLazy 'jeaye/color_coded', {
      \ 'build': {
      \   'unix': 'cmake . && make && make install',
      \ },
      \ 'augroup' : 'color_coded',
      \ 'autoload' : { 'filetypes' : ['c', 'cpp', 'objc', 'objcpp'] },
      \ 'build_commands' : ['cmake', 'make']
  \}
```

Closing.

**Comment by jeaye** [comment]
Thanks for looking into it!
